users = [
    {
    "username": "admin",
    "email": "admin@rignite.com",
    "first_name": "Adam",
    "last_name": "Minin",
    "address": "123 Main St",
    "city": "Anytown",
    "state": "CA",
    "zip_code": 12345,
    "is_admin": True,
    "password": "password"
    },
    {
    "username": "Demo-lition",
    "email": "Demo-lition@example.com",
    "first_name": "Demo",
    "last_name": "Lition",
    "address": "123 Main St",
    "city": "Anytown",
    "state": "CA",
    "zip_code": 12345,
    "is_admin": False,
    "password": "password"
    },
  {
    "username": "user1",
    "email": "user1@example.com",
    "first_name": "John",
    "last_name": "Doe",
    "address": "123 Main St",
    "city": "Anytown",
    "state": "CA",
    "zip_code": 12345,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user2",
    "email": "user2@example.com",
    "first_name": "Jane",
    "last_name": "Smith",
    "address": "456 Elm St",
    "city": "Otherville",
    "state": "NY",
    "zip_code": 67890,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user3",
    "email": "user3@example.com",
    "first_name": "Michael",
    "last_name": "Johnson",
    "address": "789 Oak St",
    "city": "Sometown",
    "state": "TX",
    "zip_code": 54321,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user4",
    "email": "user4@example.com",
    "first_name": "Emily",
    "last_name": "Anderson",
    "address": "101 Maple Ave",
    "city": "Villagetown",
    "state": "IL",
    "zip_code": 13579,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user5",
    "email": "user5@example.com",
    "first_name": "William",
    "last_name": "Brown",
    "address": "202 Pine Rd",
    "city": "Suburbia",
    "state": "FL",
    "zip_code": 24680,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user6",
    "email": "user6@example.com",
    "first_name": "Sophia",
    "last_name": "Wilson",
    "address": "303 Cedar Ln",
    "city": "Townsville",
    "state": "OH",
    "zip_code": 98765,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user7",
    "email": "user7@example.com",
    "first_name": "James",
    "last_name": "Lee",
    "address": "404 Birch Blvd",
    "city": "Hamlet",
    "state": "GA",
    "zip_code": 54321,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user8",
    "email": "user8@example.com",
    "first_name": "Olivia",
    "last_name": "Garcia",
    "address": "505 Spruce Ave",
    "city": "Cityville",
    "state": "MI",
    "zip_code": 24680,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user9",
    "email": "user9@example.com",
    "first_name": "Noah",
    "last_name": "Martinez",
    "address": "606 Oakwood Dr",
    "city": "Metropolis",
    "state": "WA",
    "zip_code": 13579,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user10",
    "email": "user10@example.com",
    "first_name": "Ava",
    "last_name": "Hernandez",
    "address": "707 Elmwood Pl",
    "city": "Townsville",
    "state": "PA",
    "zip_code": 54321,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user11",
    "email": "user11@example.com",
    "first_name": "Liam",
    "last_name": "Lopez",
    "address": "808 Maplewood Ave",
    "city": "Hamlet",
    "state": "IN",
    "zip_code": 24680,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user12",
    "email": "user12@example.com",
    "first_name": "Isabella",
    "last_name": "Rivera",
    "address": "909 Willow Ln",
    "city": "Villagetown",
    "state": "NJ",
    "zip_code": 13579,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user13",
    "email": "user13@example.com",
    "first_name": "Mason",
    "last_name": "Gonzalez",
    "address": "1010 Oak St",
    "city": "Suburbia",
    "state": "TX",
    "zip_code": 54321,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user14",
    "email": "user14@example.com",
    "first_name": "Emma",
    "last_name": "Perez",
    "address": "1111 Elm Rd",
    "city": "Cityville",
    "state": "FL",
    "zip_code": 24680,
    "is_admin": False,
    "password": "password"
  },
  {
    "username": "user15",
    "email": "user15@example.com",
    "first_name": "Alexander",
    "last_name": "Sanchez",
    "address": "1212 Maple Pl",
    "city": "Metropolis",
    "state": "NY",
    "zip_code": 13579,
    "is_admin": False,
    "password": "password"
  }
]
